kind: Deployment
apiVersion: apps/v1
metadata:
  name: liberty
  labels:
    k8s-app: liberty
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      k8s-app: liberty
  template:
    metadata:
      labels:
        k8s-app: liberty
      name: liberty
    spec:
      containers:
      - name: liberty
        image: websphere-liberty
        resources: {}
        terminationMessagePolicy: File
        imagePullPolicy: Always